<a href="https://colab.research.google.com/github/ashokdhakad/Javia-assignments/blob/master/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!python -m pip install jovian --upgrade -q
import jovian


# PyTorch functions for operations on tensors

An short introduction about PyTorch and about the chosen functions. 

- torch.from_numpy
- torch.complex
- torch.hstack
- tensor.narrow
- torch.transpose

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html
  Attempting uninstall: torch
    Found existing installation: torch 0.4.1
    Uninstalling torch-0.4.1:
      Successfully uninstalled torch-0.4.1
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.1.6
    Uninstalling torchvision-0.1.6:
      Successfully uninstalled torchvision-0.1.6


Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


In [ ]:
# Import torch and other required modules
import torch

In [ ]:
import numpy as np



# This is formatted as code

## Function 1 - torch.from_numpy

Creates a Tensor from a numpy.ndarray. The returned tensor and ndarray share the same memory. Modifications to the tensor will be reflected in the ndarray and vice versa. The returned tensor is not resizable.

In [ ]:
# Example 1 - working 
arr = np.array([[1,2,3],[5,6,7]])

ten = torch.from_numpy(arr)
print(ten)
print(ten.dtype)

tensor([[1, 2, 3],
        [5, 6, 7]], dtype=torch.int32)
torch.int32


The above example shows how a 2D numpy array has been converted to tensor of int64.

In [ ]:
# Example 2 - working
arr1 = np.random.randn(5,5)
print(arr1)
print(arr1.dtype)

t1 = torch.from_numpy(arr1)
print(t1)
print(t1.dtype)

[[-0.66540852 -0.92414309  0.08709296 -1.37452946  0.50760422]
 [ 1.00351854 -2.4704621  -0.69684151 -0.17373582  0.9264806 ]
 [-0.83696218  1.51966587 -0.61574608  0.18435946 -0.09853379]
 [-0.54145383 -0.44714845 -0.91810112 -0.5901262  -0.62310574]
 [ 0.97356119  1.3755779  -0.02834572  0.85799214  0.44058152]]
float64
tensor([[-0.6654, -0.9241,  0.0871, -1.3745,  0.5076],
        [ 1.0035, -2.4705, -0.6968, -0.1737,  0.9265],
        [-0.8370,  1.5197, -0.6157,  0.1844, -0.0985],
        [-0.5415, -0.4471, -0.9181, -0.5901, -0.6231],
        [ 0.9736,  1.3756, -0.0283,  0.8580,  0.4406]], dtype=torch.float64)
torch.float64


Example 2 shows how numpy array of shape 5x5 is transformed into tensor of same float64 data type.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = np.array([[1,2,3],['a','b','c']])
print(arr2.dtype)

t3 = torch.from_numpy(arr2)

<U11


TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

The array, arr2 has datatypes strings in one of the sub arrays. This is not supported by the tensors. As mentioned in the error, the only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

Closing comments about when to use this function:

You could use the from_numpy function when you want to convert an numpy array into a tensor, given you respect the tensor restrictions.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


In [ ]:
import jovian

In [ ]:
jovian.commit(project='Assignment-1')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Creating a new project "ashokdhakad/Assignment-1"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ashokdhakad/assignment-1


'https://jovian.ai/ashokdhakad/assignment-1'

## Function 2 - torch.complex

Constructs a complex tensor with its real part equal to real and it's imaginary part equal to imag. Takes two tensors as input and outs one complex tensor.

In [ ]:
# Example 1 - working
real = torch.tensor([1,2], dtype = torch.float32)
imag = torch.tensor([3,4], dtype=torch.float32)

z = torch.complex(real,imag)
print(z.dtype)
print(z)

torch.complex64
tensor([1.+3.j, 2.+4.j])


The above example shows how to contruct a complex tensor by joining a real and imaginaroy part of tensors.
Note that, when real and imag are of data type float32 the output has a complex of datatype complex64.

In [ ]:
# Example 2 - working
real = torch.tensor([[1,2,3],[7,8,9]], dtype = torch.float64)
imag = torch.tensor([[11,12,13],[87,89,7878]], dtype = torch.float64)

z = torch.complex(real, imag)
print(z)
print(z.dtype)

tensor([[1.+11.j, 2.+12.j, 3.+13.j],
        [7.+87.j, 8.+89.j, 9.+7878.j]], dtype=torch.complex128)
torch.complex128


The above example shows that complex accepts real and imag with same dtype. Also now that the dtype are of float64, the output complex has a datatype of complex128.



In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
real = torch.tensor([[1,2,3],[7,8,9]], dtype = torch.int64)
imag = torch.tensor([[11,12,13],[87,89,7878]], dtype = torch.int64)

z = torch.complex(real, imag)
print(z)
print(z.dtype)

RuntimeError: Expected both inputs to be Float or Double tensors but got Long and Long

The torch.complex function only accepts real and imag tensors with datatypes of float or double and both of them should have similar datatypes for it to function.

Closing comments about when to use this function:

torch.complex function is really useful in building complex equation real quick. Just keep in mind the limitations of this function.

In [ ]:
jovian.commit(project='Assignment-1')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ashokdhakad/assignment-1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ashokdhakad/assignment-1


'https://jovian.ai/ashokdhakad/assignment-1'

## Function 3 - torch.hstack

The above function helps stack tensors in sequence horizontally (column wise). Takes multiple tensors as input and returns one concatanated tensor as output.

In [ ]:
# Example 1 - working
t1 = torch.tensor([1, 2, 3, 5, 6])
print(t1.dtype, end='\n\n')
t2 = torch.tensor([4, 5, 6, 7, 8])
print(t2.dtype, end='\n\n')

t3 = torch.hstack((t1,t2))
print(t3)
print(t3.dtype)

torch.int64

torch.int64

tensor([1, 2, 3, 5, 6, 4, 5, 6, 7, 8])
torch.int64


Explanation about example1:
- t3 is a result of horizontal contactination of two tensors t1 & t2. The datatype remained same as t1 & t2.

In [ ]:
# Example 2 - working
t1 = torch.tensor([[1.5],[2.5],[3.5]])
print(t1.dtype, t1.shape, end='\n\n')
t2 = torch.tensor([[4],[5],[6]])
print(t2.dtype, t2.shape, end='\n\n')
t3 = torch.hstack((t1,t2))
print(t3)
print(t3.dtype, t3.shape)

torch.float32 torch.Size([3, 1])

torch.int64 torch.Size([3, 1])

tensor([[1.5000, 4.0000],
        [2.5000, 5.0000],
        [3.5000, 6.0000]])
torch.float32 torch.Size([3, 2])


Explanation about example:
- This example has two tensors with same size of [3,1] but with different datatypes of float32 and int64, the resultant tensor has a datatype of float32 as the entire tensor has been converted into suitable, one datatype.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

t1 = torch.tensor([[1.5],[2.5],[3.5]])
print(t1.dtype, t1.shape, end='\n\n')
t2 = torch.tensor([[4],[5]])
print(t2.dtype, t2.shape, end='\n\n')
t3 = torch.hstack((t1,t2))
print(t3)
print(t3.dtype, t3.shape)


torch.float32 torch.Size([3, 1])

torch.int64 torch.Size([2, 1])



RuntimeError: Sizes of tensors must match except in dimension 1. Got 3 and 2 in dimension 0 (The offending index is 1)

Explanation about example:
- passing tensors with different dimensions to the hstack function breaks it.
- As the error suggests, sizes of tensors must match for it to work.

Closing comments about when to use this function:
- tensor.hstack function comes in handy when you want to join multiple tensors, just be cautious about their datatypes and shape. Remember to pass in tensors of same dtype as arguements.

In [ ]:
jovian.commit(project='Assignment-1')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ashokdhakad/assignment-1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ashokdhakad/assignment-1


'https://jovian.ai/ashokdhakad/assignment-1'

## Function 4 - tensor.narrow

This function returns a new tensor that is a narrowed version of input tensor. Takes multiple arguments such as input, dim, start, length. The returned tensor and the input tensor share the same memory.

In [ ]:
# Example 1 - working
t4 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(t4)

nar_0 = torch.narrow(t4, 0, 1, 2)
print(nar_0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[4, 5, 6],
        [7, 8, 9]])


Explanation about example:
- The above function extracts a subset of the tensor t4 by starting at index 1, dimention 0 (specifies rows) and the length of 2 which grabs 2 rows out of 3.

In [ ]:
# Example 2 - working
print(t4)

nar_1 = torch.narrow(t4, 1, 0, 2)
print(nar_1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2],
        [4, 5],
        [7, 8]])


Explanation about example:
- The above function has been sliced vertically when you pass a dimention 1, it is starting at 0 index for columns and grabs 2 of them.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
print(t4)

nar_1 = torch.narrow(t4, 1, 0, 4)
print(nar_1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


RuntimeError: start (0) + length (4) exceeds dimension size (3).

Explanation about example:
 - touch.narrow function breaks when you pass the dimension greater than the dimension of the input tensor.

Closing comments about when to use this function:
- touch.narrow function is helpful in subsetting tensors and having multiple inputs makes it easier to mention the shape and size of the subset tensor.

In [ ]:
jovian.commit(project='Assignment-1')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ashokdhakad/assignment-1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ashokdhakad/assignment-1


'https://jovian.ai/ashokdhakad/assignment-1'

## Function 5 - torch.transpose

The above function returns a tensor that is a transposed version of input. This function accpets parameters as input, dim0, and dim1. The given dimensions dim0 & dim1 are swapped.

In [ ]:
# Example 1 - working
tt1 = torch.randn(5,3)
print(tt1)

tran1 = torch.transpose(tt1, 0, 1)
print(tran1)

tensor([[-6.4652e-01,  1.2283e+00, -6.5223e-01],
        [ 8.8932e-01, -5.2511e-04, -1.4620e+00],
        [-1.4532e+00, -2.1534e+00,  5.2240e-01],
        [-2.4678e-02, -5.2924e-01, -1.6293e-01],
        [ 2.3136e+00,  8.8220e-01,  2.0149e+00]])
tensor([[-6.4652e-01,  8.8932e-01, -1.4532e+00, -2.4678e-02,  2.3136e+00],
        [ 1.2283e+00, -5.2511e-04, -2.1534e+00, -5.2924e-01,  8.8220e-01],
        [-6.5223e-01, -1.4620e+00,  5.2240e-01, -1.6293e-01,  2.0149e+00]])


Explanation about example:
- The above function transposed the tensor of size [5,3] to a tensor of size [3,5]. 0, 1 in the above example denotes that they'd be transposed.

In [ ]:
# Example 2 - working
print(tt1)

tran2 = torch.transpose(tt1, 1, 0)
print(tran2)

tensor([[-6.4652e-01,  1.2283e+00, -6.5223e-01],
        [ 8.8932e-01, -5.2511e-04, -1.4620e+00],
        [-1.4532e+00, -2.1534e+00,  5.2240e-01],
        [-2.4678e-02, -5.2924e-01, -1.6293e-01],
        [ 2.3136e+00,  8.8220e-01,  2.0149e+00]])
tensor([[-6.4652e-01,  8.8932e-01, -1.4532e+00, -2.4678e-02,  2.3136e+00],
        [ 1.2283e+00, -5.2511e-04, -2.1534e+00, -5.2924e-01,  8.8220e-01],
        [-6.5223e-01, -1.4620e+00,  5.2240e-01, -1.6293e-01,  2.0149e+00]])


Explanation about example:
- The above function transposed the tensor of size [5,3] to a tensor of size [3,5]. 1,0  in the above example denotes that they'd be transposed.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
tran2 = torch.transpose(tt1,1, 2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Explanation about example:
 - Dimensions for the transpose were out of range. Expecting to get the 0,1 or 1,2 but got different numbers which were out of range.

Closing comments about when to use this function:
 - transpose function is very helpful when you want to do matrix multiplication of tensors with same shape( matrix multiplication is not possible on matrices with same shape), hence the transpose of them is required.

In [ ]:
jovian.commit(project='Assignment-1')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ashokdhakad/assignment-1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ashokdhakad/assignment-1


'https://jovian.ai/ashokdhakad/assignment-1'

## Conclusion

The functions discussed are one of the important ones while doing tensor operations. 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [ ]:
jovian.commit(project='Assignment-1')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ashokdhakad/assignment-1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ashokdhakad/assignment-1


'https://jovian.ai/ashokdhakad/assignment-1'

In [ ]:
jovian.submit(project='Assignment-1',assignment="zerotogans-a1")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ashokdhakad/assignment-1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ashokdhakad/assignment-1
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor
